[package]
name = "pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
cursive = "0.19.0"
magic-crypt = "3.1.12"
sha3 = "0.10.8"
